config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurant_profiles#index'

  # devise_for :restaurants
  devise_for :customers

  devise_for :restaurants, controllers: {
      registrations: 'restaurants/registrations'
  }

  resources :restaurant_profiles do
    resources :menu_items, except: [:index, :show]
  end

  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, except: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/views/customer_profiles/_form.html.erb
<%= form_for @customer_profile do |f| %>
  <%= f.label :firstname %>
  <%= f.text_field :firstname %>
  <%= f.label :lastname %>
  <%= f.text_field :lastname %>
  <%= f.label :about %>
  <%= f.text_area :about %>
  <%= f.label :interests %>
  <%= f.text_field :interests %>
  <%= f.submit %>
<% end %>

app/views/customer_profiles/edit.html.erb
<h1>Editing Restaurant Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_profile %> |
<%= link_to 'Back', customer_profile_path(@customer_profile) %> |
<%= link_to 'Destroy', @customer_profile, method: :delete, data: { confirm: 'Are you sure you want to destroy this account?' } %>

app/views/customer_profiles/show.html.erb
<div class="profile customer-profile">

    <h3 class="customer-name"> <%= @customer_profile.firstname %> <%= @customer_profile.lastname %></h3>
    <h4 class="about"> <%= @customer_profile.about %> </h4>
    <h4 class="interests"> <%= @customer_profile.interests %> </h4>

</div>

<% if current_customer == @customer_profile.customer  %>
  <%= link_to 'Edit Profile', edit_customer_profile_path(@customer_profile) %> |
<% end %>