config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurant_profiles#index'

  # devise_for :restaurants
  devise_for :customers

  devise_for :restaurants, controllers: {
      registrations: 'restaurants/registrations'
  }

  resources :restaurant_profiles do
    resources :menu_items, except: [:index, :show]
  end

  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, except: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items

  def add_menu_item(menu_item_params)
    # Indentation
    new_item = cart_items.create(menu_item_id: menu_item_params[:menu_item][:menu_item_id],
                                cart_id: self.id)
    new_item
  end

  def cart_size
    size = 0
    self.cart_items.each do |cart_item|
      size += 1
    end
    size
  end


  # Commented code should be kept in a feature branch until ready,
  # and not pushed to `master`
  # def total_price
  #   cart_items.to_a.sum { |item| item.total_price }
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:index]

  def index
  end

end

app/views/carts/_cart_row.html.erb
<div class="row">
    <%= form_for order_item, remote: true do |f| %>
      <div class="row">
          <%= link_to "Delete", order_item, { method: :delete, remote: true, class: "button" } %>
      </div>
    <% end %>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@cart_item.nil? && @cart_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @cart_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @cart_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @cart_items.each do |cart_item| %>
    <%= render 'carts/cart_row', menu_item: cart_item.menu_item, cart_item: cart_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<!-- <div class="shopping-cart">
  <%#= render "shopping_cart" %>
</div> -->
<div class="container">
  <h1>Your Cart</h1>
  <table class="cart container flex column">
    <thead>
      <tr>
        <!-- <th>Picture</th>
        <th>Item</th>
        <th>Restaurant</th> -->
      </tr>
    </thead>

  <tbody>
      <% current_cart.cart_items.each do |item| %>
        <tr class="flex row justify-space">
          <td><%= link_to image_tag(item.menu_item.image_url, class: "image"), restaurant_profile_path(item.menu_item.restaurant_profile)  %></td>
          <td><%= link_to item.menu_item.restaurant_profile.name, restaurant_profile_path(item.menu_item.restaurant_profile) %></td>
          <td><%= link_to 'Remove', cart_item_url(item), method: :delete, class: "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <div class="finalize">
    <%= link_to 'Order Items', new_order_path, class: "button" %>
  </div>
</div>