config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurant_profiles#index'

  # devise_for :restaurants
  devise_for :customers

  devise_for :restaurants, controllers: {
      registrations: 'restaurants/registrations'
  }

  resources :restaurant_profiles do
    resources :menu_items, except: [:index, :show]
  end

  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, except: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/models/restaurant_profile.rb
class RestaurantProfile < ApplicationRecord
  belongs_to :restaurant

  has_many :menu_items, dependent: :destroy
end

app/controllers/restaurant_profiles_controller.rb
class RestaurantProfilesController < ApplicationController
  before_action :set_restaurant_profile, only: [:show, :edit, :update, :destroy]

  def index
    @restaurant_profiles = RestaurantProfile.all
  end

  def show
    @menu_item = @restaurant_profile.menu_items.all.sample
  end

  def new
    @restaurant_profile = RestaurantProfile.new
  end

  def edit
  end

  def create
    # If we merge the restaurant in with our profile params, we can create the
    # profile in one action
    @restaurant_profile = RestaurantProfile.create!(restaurant_profile_params.merge({
      restaurant: current_restaurant
      }))
    # @restaurant_profile.restaurant = current_restaurant
    flash[:notice] = "Profile was successfully created."
    redirect_to restaurant_profile_path(@restaurant_profile)
  end

  def update
    @restaurant_profile.update(restaurant_profile_params)
    flash[:notice] = "profile was updated."
    redirect_to restaurant_profile_path(@restaurant_profile)
  end

  def destroy
    @restaurant_profile.destroy
    @restaurant_profile.restaurant.destroy
    flash[:notice] = "user was successfully destroyed."
    redirect_to restaurant_profiles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_profile
      @restaurant_profile = RestaurantProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_profile_params
      params.require(:restaurant_profile).permit(:name, :address, :description)
    end
end

app/views/restaurant_profiles/_form.html.erb
<div class="container">
  <%= form_for @restaurant_profile do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurant_profiles/_links.html.erb
<div class="links">
  <% if current_restaurant == restaurant_profile.restaurant  %>
    <%= link_to 'New Menu Item', new_restaurant_profile_menu_item_path(restaurant_profile) %> |
    <%= link_to 'Edit Profile', edit_restaurant_profile_path(restaurant_profile) %> |
  <% end %>

  <%= link_to 'Back', restaurant_profiles_path %>
</div>

app/views/restaurant_profiles/_menu.html.erb
<div class="menu">
  <h3> Menu: </h3>
  <% restaurant_profile.menu_items.each do |item| %>
    <div class="menu-item">
      <%= item.name %>: <i><%= item.description %></i>
      <% if current_restaurant == restaurant_profile.restaurant %>
        <%= link_to ' - Edit Item', edit_restaurant_profile_menu_item_path(restaurant_profile, item) %>
      <% end %>
    </div>
  <% end %>

  <% if current_restaurant %>
    <%= link_to 'Create New Item', new_restaurant_profile_menu_item_path(restaurant_profile) %>
  <% end %>

</div>

app/views/restaurant_profiles/_order.html.erb
<div class="row">

    <%= form_for menu_item, :url => cart_items_path, :html => { :method => :post } do |f|%>
        <%= f.hidden_field :menu_item_id, value: menu_item.id %>
        <%= f.submit 'Add to Cart', class: "button" %>
    <% end %>
</div>

app/views/restaurant_profiles/edit.html.erb
<h1>Editing Restaurant Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_profile %> |
<%= link_to 'Back', restaurant_profiles_path %> |
<%= link_to 'Destroy', @restaurant_profile, method: :delete, data: { confirm: 'Are you sure you want to destroy this account?' } %>

app/views/restaurant_profiles/index.html.erb
<div class="restaurant-profiles flex column align-center">
  <% @restaurant_profiles.each do |restaurant_profile| %>
  <div class="restaurant container">
    <h3 class="name"> <%= link_to restaurant_profile.name, restaurant_profile  %></h3>
    <p ><%= restaurant_profile.description %></p>
    <h3 class="profile-pic"> <%#= link_to restaurant_profile.profile_pic, restaurant_profile  %></h3>

  </div>
  <% end %>

</div>

app/views/restaurant_profiles/new.html.erb
<h1>New Restaurant Profile</h1>

<%= render 'form' %>

app/views/restaurant_profiles/show.html.erb
<div class="restaurant-profile container flex row">

    <div class="restaurant-details flex column">
      <h2 class="restaurant-name"> <%= @restaurant_profile.name %> </h2>
      <p class="address"> <%= @restaurant_profile.address %> </p>
      <p class="description"> <%= @restaurant_profile.description %> </p>

      <% if current_customer %>
        <%= render "order", menu_item: @menu_item, order_item: @order_item %>
      <% end %>

      <%= render "links", restaurant_profile: @restaurant_profile %>

    </div>

    <%= render "menu", restaurant_profile: @restaurant_profile %>

</div>