config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurant_profiles#index'

  # devise_for :restaurants
  devise_for :customers

  devise_for :restaurants, controllers: {
      registrations: 'restaurants/registrations'
  }

  resources :restaurant_profiles do
    resources :menu_items, except: [:index, :show]
  end

  resources :cart_items, only: [:create, :update, :destroy]
  resources :orders, except: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/views/layouts/_cart_text.html.erb
<i class="fa fa-shopping-cart fa-2x" aria-hidden="true"><%= link_to " #{current_cart.cart_size} Items ", cart_path, class: "button" %></i>

app/views/layouts/_user.html.erb
<% if current_restaurant || current_customer %>

  <% if current_restaurant %>
    <!--
      When a new restauant is created during sign up, this restaurant-user doesn't
      yet have a `profile` assigned. Generating this profile link fails with
      "undefined method `name' for nil:NilClass"
      To handle this edge case, we should be sure to only use `profile` if it exists.
    -->
    <% if profile %>
    <%= link_to profile.name, restaurant_profile_path(profile) %>
    <% else %>
    <%= "Unnamed Restaurant" %>
    <% end %>
    <%= link_to "Sign Out", destroy_restaurant_session_path, :method => :delete %>
  <% else %>
    <%= current_customer.email %>
    <!-- <%#= link_to profile.firstname + " " + profile.lastname, customer_profile_path(profile) %> -->
    <%= link_to "Sign Out", destroy_customer_session_path, :method => :delete %>
  <% end %>

<% else %>


  <div class="auth">
    Restaurant
    <%= link_to "Sign In", new_restaurant_session_path %>/<%= link_to "Sign Up", new_restaurant_registration_path %>
  </div>

  <div class="auth">
    Customer
      <%= link_to "Sign In", new_customer_session_path %>/<%= link_to "Sign Up", new_customer_registration_path %>
  </div>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>MysteryLunch</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Saira" rel="stylesheet">
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/42cf8c2449.js"></script>
  </head>

  <body class="flex column">

    <div class="header justify-between flex row">

      <!-- <div class="border justify-between flex row"> -->
        <h1 class="title"><%= link_to "Mystery Lunch", root_path %></h1>
        <div class="user flex row">

          <% if current_customer %>
            <h3 class="cart-text end"><%= render 'layouts/cart_text' %></h3>
          <% end %>


          <div class="users flex column justify-between">
            <%= render 'layouts/user' %>
          </div>

        </div>

      <!-- </div> -->

  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="content flex column align-center">
    <%= yield %>
  </div>

  </body>
</html>